<?php

namespace Softspring\CrudlBundle\Helper;

use Softspring\Component\CrudlController\Event\FormPrepareEvent;
use Softspring\Component\CrudlController\Helper\ListActionHelper as BaseListActionHelper;
use Softspring\CrudlBundle\Form\DefaultFilterForm;
use Symfony\Component\Form\FormInterface;

class ListActionHelper extends BaseListActionHelper
{
    public function dispatchFormPrepare(array $options = null): FormPrepareEvent
    {
        if (null === $options) {
            $options = [
                'method' => 'GET',
            ];

            if (is_array($this->config['filter_form'])) {
                $options = array_merge($options, $this->config['filter_form']);
            }
        }

        return parent::dispatchFormPrepare($options);
    }

    public function createFilterForm(FormPrepareEvent $formPrepareEvent): ?FormInterface
    {
        $type = $formPrepareEvent->getType();

        if (is_string($type) && DefaultFilterForm::class !== $type) {
            return parent::createFilterForm($formPrepareEvent); // TODO: Change the autogenerated stub
        }

        $formOptions = $formPrepareEvent->getFormOptions();
        $formOptions['manager'] = $this->manager;

        $this->filterForm = $this->formFactory->create(DefaultFilterForm::class, [], $formOptions);

        $this->filterForm->handleRequest($this->request);

        return $this->filterForm;
    }
}
