<?php

namespace Softspring\CrudlBundle\Helper;

use Softspring\Component\CrudlController\Event\FormPrepareEvent;
use Softspring\Component\CrudlController\Helper\ListActionHelper as BaseListActionHelper;
use Softspring\CrudlBundle\Form\DefaultFilterForm;
use Symfony\Component\Form\FormInterface;

class ListActionHelper extends BaseListActionHelper
{
    public function createFilterForm(FormPrepareEvent $formPrepareEvent): ?FormInterface
    {
        $type = $formPrepareEvent->getType();

        if (is_string($type) && DefaultFilterForm::class !== $type) {
            return parent::createFilterForm($formPrepareEvent); // TODO: Change the autogenerated stub
        }

        $formOptions = $formPrepareEvent->getFormOptions();
        $formOptions['manager'] = $this->manager;

        if (is_array($type)) {
            $formOptions['filter_fields'] = $type['filter_fields'] ?? null;
            $formOptions['order_valid_fields'] = $type['order_valid_fields'] ?? null;
            $formOptions['order_default_value'] = $type['order_default_value'] ?? null;

            if (isset($type['order_direction_default_value'])) {
                $formOptions['order_direction_default_value'] = $type['order_direction_default_value'];
            }
        }

        $this->filterForm = $this->formFactory->create(DefaultFilterForm::class, [], $formOptions);

        $this->filterForm->handleRequest($this->request);

        return $this->filterForm;
    }
}
